### PR TITLE
rootless random UI container image builds & lots of refactor and cleanup

### PR DESCRIPTION
**Pull request by itewk**
# Purpose
* standerdize chart names
* update to be able to do container image builds in a rootless random UID container
* fix where certain shared resources are stored for use by both jenkins/tekton/future workflow runners

# breaking
* chart name changes
* removal of some chart parameters for old fixed UID way of doing things
* probably some other stuff

# related
* https://github.com/ploigos/ploigos-containers/pull/67
* https://github.com/ploigos/ploigos-jenkins-library/pull/41

### CODE REVIEW

**Comment by itewk** [comment]
merging without review. trust me. i did lots of testing and no one wants to review this.

**Comment by dwinchell** [comment]
Do the Jenkins related charts do anything right now? Looks like maybe just framework.

And yeah, 85 files changed and it's all Helm to configure Tekton ... I'll pass on the review.

**Comment by itewk** [comment]
@dwinchell yes-ish. Basicaly its a wrapper for the `ploigos-workflow-shared-resources` chart and doesnt layer anything else on top, right now. But the assumption is maybe one day there will be something jenkins specific, such as if you are using the jenkins operator and configuring your pipelines via kube resources. Also, it annoyed me that for the jenkins ref projects they pointed at `ploigos-workflow-shared-resources` and it wasn't clear why, and makes it more clear to piont at `ploigos-workflow-jenkins-resources` even though right now its a thin vail.

**Comment by itewk** [comment]
most of the file changes it hat i had to move things around do to file pathing/naming/length/testing annoying issues that i documented in a readme

**Pull request merged**
